// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lymsduvzqtkjkvlwieme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5bXNkdXZ6cXRramt2bHdpZW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQ0OTMsImV4cCI6MjA3Mzc5MDQ5M30.GQ99mXFc13zHpL6FkGErTwQzb1p-TyU3eAANSEe4xNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});